#Create a volume named - healthcecks-data first in portainer before creating this stack
version: "3"
services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:
      - ALLOWED_HOSTS=localhost
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=<<add-tour email here>>
      - EMAIL_HOST=smtp.gmail.com #If using Gmail SMTP
      - EMAIL_HOST_PASSWORD=<<Gmail-app-password>>
      - EMAIL_HOST_USER=<<add-your-email here>>
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
   #   - SECRET_KEY=
      - SITE_ROOT=http://<home-ip>:8010 #(Example -http://10.10.1.20:8010)
      - ALLOWED_HOSTS=*
    ports:
      - 8010:8000
    volumes:
      - healthchecks-data:/data
    restart: unless-stopped
volumes:
    healthchecks-data: 
