version: '3.1'

services:
  openhab:
    image: openhab/openhab
    container_name: openhab
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/valyria/openhab/addons:/openhab/addons
      - /home/valyria/openhab/conf:/openhab/conf
      - /home/valyria/openhab/userdata:/openhab/userdata
    environment:
      CRYPTO_POLICY: unlimited
      EXTRA_JAVA_OPTS: -Duser.timezone=Asia/Kolkata
      OPENHAB_HTTP_PORT: 8080
      OPENHAB_HTTPS_PORT: 8443
