---
version: "3.1"
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment: #Your PUID and PGID might be different. SSH into your server and run the command "id" without quotes to get your PUID/PGID
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/valyria/config/filezilla/:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
