---
version: "3.1"
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Kolkata
    volumes:
      - /home/valyria/config/filezilla/:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
